# Generated by Django 5.0.1 on 2025-11-24 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="智能体名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "system_prompt",
                    models.TextField(blank=True, null=True, verbose_name="系统提示词"),
                ),
                (
                    "user_prompt_template",
                    models.TextField(
                        blank=True, null=True, verbose_name="用户提示词模板"
                    ),
                ),
                (
                    "model_config",
                    models.JSONField(default=dict, verbose_name="模型配置"),
                ),
                (
                    "workflow_id",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="关联工作流ID"
                    ),
                ),
                (
                    "knowledge_base_ids",
                    models.JSONField(default=list, verbose_name="关联知识库ID列表"),
                ),
                (
                    "plugin_ids",
                    models.JSONField(default=list, verbose_name="关联插件ID列表"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "草稿"), ("published", "已发布")],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, verbose_name="逻辑删除"),
                ),
            ],
            options={
                "verbose_name": "智能体",
                "verbose_name_plural": "智能体",
                "db_table": "agent",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status"], name="agent_status_ae5860_idx"),
                    models.Index(
                        fields=["created_at"], name="agent_created_6150fb_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("user_message", models.TextField(verbose_name="用户消息")),
                ("assistant_message", models.TextField(verbose_name="助手回复")),
                ("context", models.JSONField(default=dict, verbose_name="上下文信息")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="agent.agent",
                        verbose_name="智能体",
                    ),
                ),
            ],
            options={
                "verbose_name": "对话记录",
                "verbose_name_plural": "对话记录",
                "db_table": "conversation",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["agent", "created_at"],
                        name="conversatio_agent_i_7bccdf_idx",
                    )
                ],
            },
        ),
    ]
