# Generated by Django 4.2.26 on 2025-12-23 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Workflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="工作流名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                ("definition", models.JSONField(default=dict, verbose_name="工作流定义")),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "草稿"), ("active", "已启用")],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("deleted", models.BooleanField(default=False, verbose_name="逻辑删除")),
            ],
            options={
                "verbose_name": "工作流",
                "verbose_name_plural": "工作流",
                "db_table": "workflow",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("input_data", models.JSONField(default=dict, verbose_name="输入数据")),
                ("output_data", models.JSONField(default=dict, verbose_name="输出数据")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待执行"),
                            ("running", "执行中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="执行状态",
                    ),
                ),
                ("node_status", models.JSONField(default=dict, verbose_name="节点执行状态")),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="完成时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="workflow.workflow",
                        verbose_name="工作流",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作流执行记录",
                "verbose_name_plural": "工作流执行记录",
                "db_table": "workflow_execution",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="workflow",
            index=models.Index(fields=["status"], name="workflow_status_idx"),
        ),
        migrations.AddIndex(
            model_name="workflow",
            index=models.Index(fields=["created_at"], name="workflow_created_idx"),
        ),
        migrations.AddIndex(
            model_name="workflowexecution",
            index=models.Index(
                fields=["workflow", "status"], name="wf_exec_workflow_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowexecution",
            index=models.Index(fields=["created_at"], name="wf_exec_created_idx"),
        ),
    ]
