# Generated by Django 5.0.1 on 2025-11-24 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Workflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="工作流名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "definition",
                    models.JSONField(
                        default=dict, verbose_name="工作流定义（节点和连线）"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "草稿"), ("active", "激活")],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, verbose_name="逻辑删除"),
                ),
            ],
            options={
                "verbose_name": "工作流",
                "verbose_name_plural": "工作流",
                "db_table": "workflow",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status"], name="workflow_status_ba89d2_idx"),
                    models.Index(
                        fields=["created_at"], name="workflow_created_de5caa_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkflowExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("input_data", models.JSONField(default=dict, verbose_name="输入数据")),
                (
                    "output_data",
                    models.JSONField(default=dict, verbose_name="输出数据"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("running", "运行中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="执行状态",
                    ),
                ),
                (
                    "node_status",
                    models.JSONField(default=dict, verbose_name="节点执行状态"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="workflow.workflow",
                        verbose_name="工作流",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作流执行记录",
                "verbose_name_plural": "工作流执行记录",
                "db_table": "workflow_execution",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["workflow", "status"],
                        name="workflow_ex_workflo_8c0c9d_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="workflow_ex_created_601f3f_idx"
                    ),
                ],
            },
        ),
    ]
