# Generated by Django 5.0.1 on 2025-11-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plugin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="插件名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                ("openapi_spec", models.JSONField(verbose_name="OpenAPI规范")),
                ("base_url", models.CharField(max_length=500, verbose_name="基础URL")),
                (
                    "auth_config",
                    models.JSONField(default=dict, verbose_name="认证配置"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("enabled", "启用"), ("disabled", "禁用")],
                        default="enabled",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "deleted",
                    models.BooleanField(default=False, verbose_name="逻辑删除"),
                ),
            ],
            options={
                "verbose_name": "插件",
                "verbose_name_plural": "插件",
                "db_table": "plugin",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status"], name="plugin_status_7bb805_idx"),
                    models.Index(
                        fields=["created_at"], name="plugin_created_c25910_idx"
                    ),
                ],
            },
        ),
    ]
